I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 90, in script
    gg "Спасибо… [в недоумении]"
KeyError: u'\u0432 \u043d\u0435\u0434\u043e\u0443\u043c\u0435\u043d\u0438\u0438'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 90, in script
    gg "Спасибо… [в недоумении]"
  File "renpy/ast.py", line 721, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "renpy/exports.py", line 1419, in say
    who(what, *args, **kwargs)
  File "renpy/character.py", line 1236, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "renpy/character.py", line 1155, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "renpy/character.py", line 1135, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "renpy/substitutions.py", line 270, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 605, in get_value
KeyError: u'\u0432 \u043d\u0435\u0434\u043e\u0443\u043c\u0435\u043d\u0438\u0438'

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Death Parade 1.0
Thu Nov 16 18:55:10 2023
